import React, { useState } from "react";
import { base44 } from "@/api/base44Client";

function cleanText(text) {
  if (!text) return '';
  return text
    .replace(/[^\x20-\x7E\n\r\t]/g, '')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n');
}

function buildEmailHtml(formData, niche, prompts) {
  const phases = prompts.map((p, i) => {
    const promptLines = cleanText(p.prompt)
      .split('\n')
      .map(line => {
        const trimmed = line.trim();
        if (!trimmed) return '<br/>';
        if (trimmed.startsWith('# ')) return `<h2 style="color:#1a1a1a;font-size:20px;margin:18px 0 8px;">${trimmed.slice(2)}</h2>`;
        if (trimmed.startsWith('## ')) return `<h3 style="color:#333;font-size:17px;margin:14px 0 6px;">${trimmed.slice(3)}</h3>`;
        if (trimmed.startsWith('### ')) return `<h4 style="color:#444;font-size:15px;margin:12px 0 4px;">${trimmed.slice(4)}</h4>`;
        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) return `<li style="margin:2px 0;margin-left:20px;">${trimmed.slice(2)}</li>`;
        if (/^\d+\.\s/.test(trimmed)) return `<li style="margin:2px 0;margin-left:20px;">${trimmed.replace(/^\d+\.\s/, '')}</li>`;
        if (trimmed.startsWith('**') && trimmed.endsWith('**')) return `<p style="margin:6px 0;"><strong>${trimmed.slice(2, -2)}</strong></p>`;
        return `<p style="margin:4px 0;line-height:1.6;">${trimmed}</p>`;
      })
      .join('\n');

    return `
      <tr><td style="padding:24px 0 8px;">
        <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e0dcd4;border-radius:8px;overflow:hidden;">
          <tr><td style="background:#1a1a1a;color:#ffffff;padding:14px 20px;">
            <strong style="font-size:16px;">Phase ${i + 1}: ${cleanText(p.title)}</strong><br/>
            <span style="font-size:12px;color:#aaa;">Optimized for: ${cleanText(p.model)}</span>
          </td></tr>
          <tr><td style="padding:16px 20px;background:#faf8f4;font-size:14px;color:#333;">
            ${promptLines}
          </td></tr>
        </table>
      </td></tr>`;
  }).join('');

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f5f3ef;font-family:Arial,Helvetica,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f3ef;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
  <tr><td style="background:#1a1a1a;padding:28px 30px;text-align:center;">
    <h1 style="color:#ffffff;font-size:22px;margin:0;">Dream 100 Partner Blueprint</h1>
    <p style="color:#C8A951;font-size:14px;margin:8px 0 0;">Your personalized referral partner system</p>
  </td></tr>
  <tr><td style="padding:24px 30px;">
    <p style="font-size:15px;color:#333;line-height:1.6;">Hi ${cleanText(formData.name)},</p>
    <p style="font-size:15px;color:#333;line-height:1.6;">Here is your complete Dream 100 Partner Blueprint for <strong>${cleanText(niche)}</strong> in <strong>${cleanText(formData.geo)}</strong>.</p>
    <p style="font-size:14px;color:#666;line-height:1.5;">Below are all 7 phases. Copy each prompt into your preferred AI tool to generate your partner strategy.</p>
  </td></tr>
  ${phases}
  <tr><td style="padding:30px;text-align:center;border-top:1px solid #e0dcd4;">
    <p style="font-size:14px;color:#666;margin:0 0 12px;">Want to make a lasting impression on your Dream 100 partners?</p>
    <a href="http://NurturInk.com/realestate" target="_blank" style="display:inline-block;background:#C8A951;color:#1a1a1a;padding:12px 28px;border-radius:6px;text-decoration:none;font-weight:bold;font-size:14px;">See How NurturInk Can Help</a>
    <p style="font-size:12px;color:#999;margin:16px 0 0;">Generated by NurturInk Dream 100 Builder<br/>pipeline.nurturink.com</p>
  </td></tr>
</table>
</td></tr>
</table>
</body></html>`;
}

export default function EmailModal({ formData, niche, prompts, onClose }) {
  const [email, setEmail] = useState('');
  const [emailError, setEmailError] = useState(false);
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);

  const handleSend = async () => {
    if (!email || !email.includes('@')) {
      setEmailError(true);
      return;
    }
    setEmailError(false);
    setSending(true);

    const htmlBody = buildEmailHtml(formData, niche, prompts);

    await base44.integrations.Core.SendEmail({
      to: email,
      subject: `Your Dream 100 Blueprint - ${niche} in ${formData.geo}`,
      body: htmlBody,
      from_name: "NurturInk Dream 100 Builder"
    });

    setSending(false);
    setSent(true);
  };

  const handleOverlayClick = (e) => {
    if (e.target === e.currentTarget) onClose();
  };

  return (
    <div className="d100-modal-overlay" onClick={handleOverlayClick}>
      <div className="d100-modal-box">
        <div className="d100-modal-handle" />
        {!sent ? (
          <>
            <h3>Email Me My Blueprint</h3>
            <p className="d100-modal-sub">We'll send your complete 7-phase blueprint to your inbox. No spam — one email, just your blueprint.</p>
            <input
              type="email"
              className="d100-input"
              value={email}
              onChange={(e) => { setEmail(e.target.value); setEmailError(false); }}
              placeholder="your@email.com"
              style={{ marginBottom: 12, borderColor: emailError ? '#DC2626' : undefined }}
            />
            <button className="d100-btn-modal-send" onClick={handleSend} disabled={sending}>
              {sending ? 'Sending...' : 'Send My Blueprint'}
            </button>
            <button className="d100-btn-modal-cancel" onClick={onClose}>Cancel</button>
            <p className="d100-modal-fine">Your email is used only to deliver your blueprint. We may occasionally share helpful resources from NurturInk. Unsubscribe anytime.</p>
          </>
        ) : (
          <div className="d100-email-success">
            <div className="checkmark" style={{ fontSize: 36, marginBottom: 12 }}>✉️</div>
            <h3>Check Your Inbox</h3>
            <p>Your blueprint is on its way!</p>
            <div style={{
              background: '#FEF3C7',
              border: '1px solid #F59E0B',
              borderRadius: 8,
              padding: '12px 16px',
              margin: '16px 0',
              fontSize: 14,
              color: '#92400E',
              lineHeight: 1.5,
              textAlign: 'left'
            }}>
              <strong>Important:</strong> The email may land in your spam or promotions folder. If you don't see it in your inbox within a few minutes, please check those folders and mark it as "Not Spam" so you don't miss it.
            </div>
            <p style={{ marginTop: 12 }}>While you're here — see how NurturInk can help you land those partners faster.</p>
            <a href="http://NurturInk.com/realestate" target="_blank" rel="noopener noreferrer" className="d100-cta-link">See NurturInk for Agents &rarr;</a>
            <br /><br />
            <button className="d100-btn-modal-cancel" onClick={onClose}>Close</button>
          </div>
        )}
      </div>
    </div>
  );
}