import React, { useState } from "react";
import { base44 } from "@/api/base44Client";

export default function EmailModal({ formData, niche, prompts, onClose }) {
  const [email, setEmail] = useState('');
  const [emailError, setEmailError] = useState(false);
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);

  const handleSend = async () => {
    if (!email || !email.includes('@')) {
      setEmailError(true);
      return;
    }
    setEmailError(false);
    setSending(true);

    const bodyText = `Hi ${formData.name},\n\nHere is your Dream 100 Partner Blueprint for ${niche} in ${formData.geo}.\n\n` +
      prompts.map((p, i) => `PHASE ${i + 1}: ${p.title}\nFor: ${p.model}\n\n${p.prompt}`).join('\n\n---\n\n') +
      `\n\n---\nGenerated by NurturInk Dream 100 Builder\nhttps://pipeline.nurturink.com\n\nLearn how NurturInk can help you land these partners:\nhttps://nurturink.com/realestate`;

    await base44.integrations.Core.SendEmail({
      to: email,
      subject: `Your Dream 100 Blueprint — ${niche} in ${formData.geo}`,
      body: bodyText,
      from_name: "NurturInk Dream 100 Builder"
    });

    setSending(false);
    setSent(true);
  };

  const handleOverlayClick = (e) => {
    if (e.target === e.currentTarget) onClose();
  };

  return (
    <div className="d100-modal-overlay" onClick={handleOverlayClick}>
      <div className="d100-modal-box">
        <div className="d100-modal-handle" />
        {!sent ? (
          <>
            <h3>Email Me My Blueprint</h3>
            <p className="d100-modal-sub">We'll send your complete 7-phase blueprint to your inbox. No spam — one email, just your blueprint.</p>
            <input
              type="email"
              className="d100-input"
              value={email}
              onChange={(e) => { setEmail(e.target.value); setEmailError(false); }}
              placeholder="your@email.com"
              style={{ marginBottom: 12, borderColor: emailError ? '#DC2626' : undefined }}
            />
            <button className="d100-btn-modal-send" onClick={handleSend} disabled={sending}>
              {sending ? 'Sending...' : 'Send My Blueprint'}
            </button>
            <button className="d100-btn-modal-cancel" onClick={onClose}>Cancel</button>
            <p className="d100-modal-fine">Your email is used only to deliver your blueprint. We may occasionally share helpful resources from NurturInk. Unsubscribe anytime.</p>
          </>
        ) : (
          <div className="d100-email-success">
            <div className="checkmark">✉️</div>
            <h3>Check Your Inbox</h3>
            <p>Your blueprint is on its way. While you're here — see how NurturInk can help you land those partners faster.</p>
            <a href="https://nurturink.com/realestate" target="_blank" rel="noopener noreferrer" className="d100-cta-link">See NurturInk for Agents →</a>
            <br /><br />
            <button className="d100-btn-modal-cancel" onClick={onClose}>Close</button>
          </div>
        )}
      </div>
    </div>
  );
}