import React, { useState } from "react";
import EmailModal from "./EmailModal";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { useTheme } from "@/components/ThemeContext";

const DL_ITEMS = [
  { icon: "📄", label: "Step-by-step usage instructions" },
  { icon: "💬", label: "10 fully personalized AI prompts" },
  { icon: "🚀", label: "Which AI tool to use for each prompt" },
  { icon: "📐", label: "How to format inputs for best results" },
  { icon: "✏️", label: "How to refine results if needed" },
  { icon: "✉️", label: "Handwritten note template (Phase 6)" },
];

const S = {
  navy:     '#1B2A4A',
  navyL:    '#243659',
  gold:     '#F0A422',
  goldL:    '#F7BC55',
  goldPale: '#FDF0D5',
  text:     '#1A1A2E',
  muted:    '#5A6278',
  border:   '#DDD5C5',
  bg:       '#F4F1EC',
  white:    '#ffffff',
  success:  '#2D6A4F',
  warnBg:   '#FEF3C7',
  warnBd:   '#F59E0B',
  warnText: '#92400E',
};

export default function OutputView({ formData, prompts, onRestart }) {
  const navigate = useNavigate();
  const { theme } = useTheme();
  const [emailModalOpen, setEmailModalOpen] = useState(false);
  const [dlLabel, setDlLabel] = useState('↓ Download Your Blueprint');

  React.useEffect(() => {
    const handler = () => setEmailModalOpen(true);
    document.addEventListener('openEmailModal', handler);
    return () => document.removeEventListener('openEmailModal', handler);
  }, []);

  const niche = formData.customNiche
    ? `${formData.nicheBase} — ${formData.customNiche}`
    : formData.nicheBase || '';

  const cleanText = (text) => {
    if (!text) return '';
    return text.replace(/[^\x20-\x7E\n\r\t]/g, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  };

  const downloadAll = () => {
    const divider = '='.repeat(60);
    const thinDivider = '-'.repeat(60);

    // ── INSTRUCTIONS SECTION ──
    const instructions = `${divider}
DREAM 100 PARTNER BLUEPRINT
${divider}

${cleanText(niche)} | ${cleanText(formData.geo)}
Generated for: ${cleanText(formData.name)}
Generated by ${theme.brandName} - ${theme.brandUrl}


${divider}
HOW TO USE THIS DOCUMENT
${divider}

This document contains 7 AI prompts that will build your complete
Dream 100 referral partner system. Each prompt is designed to be
copied and pasted into an AI tool like ChatGPT, Claude, or Gemini.

IMPORTANT: These prompts are designed to be run IN ORDER. Each phase
builds on the results of the previous one. Do NOT skip ahead.


STEP-BY-STEP INSTRUCTIONS
${thinDivider}

1. OPEN YOUR AI TOOL
   Go to chat.openai.com (ChatGPT), claude.ai, or your preferred AI.
   Start a NEW conversation for each phase.

2. COPY THE PROMPT
   Select everything between the START and END markers for each phase.
   Copy it and paste it into your AI tool.

3. REVIEW THE OUTPUT
   Read through the AI's response. If anything seems off or too
   generic, tell the AI what to fix -- it will revise.

4. SAVE THE OUTPUT
   Copy or save the AI's response before moving to the next phase.
   You will need it.

5. CHAIN THE RESULTS (THIS IS THE KEY)
   Starting with Phase 2, you need to include the relevant output
   from the previous phase. Before pasting the next prompt, paste
   the previous phase's output and say:

   "Here are my results from the previous phase. Use these as
   context for the next prompt I'm about to give you:"

   Then paste the previous output, hit enter, and THEN paste the
   next prompt.


WHICH PHASES NEED PREVIOUS RESULTS?
${thinDivider}

Phase 1  No prior results needed. Just paste and go.

Phase 2  Include your Phase 1 output (lifecycle triggers).
         The AI uses your trigger events to identify which
         professionals see your clients at those moments.

Phase 3  Include your Phase 2 output (partner types).
         The AI uses your partner map to build and rank
         your Dream 5 list. This is the most important
         phase -- everything after this references it.

Phase 4  Include your Phase 3 output (Dream 5 list).
         The AI builds value strategies for all 5 of your
         Dream partners plus your Value Manifesto.

Phase 5  Include Phase 3 output and Phase 4 output.
         The AI references your specific partner types and
         value gifts when crafting objection responses.

Phase 6  Include Phase 3 and Phase 4 output.
         The AI writes scripts that reference the exact
         partner types and value gifts you've established.

Phase 7  Include Phase 3 and Phase 4 output.
         The AI builds your 90-day plan, relationship
         tracker, 12-month calendar, and referral math.


HOW TO CHAIN (EXAMPLE)
${thinDivider}

When starting Phase 2, your message to the AI would look like:

   "Here are my results from Phase 1 (Lifecycle Trigger Mapping).
   Use these as context for the next prompt:

   [paste your Phase 1 output here]

   Now here is my Phase 2 prompt:

   [paste the Phase 2 prompt from this document]"

That's it. The AI will use the context automatically.


TIPS FOR BEST RESULTS
${thinDivider}

- Use the SAME AI tool for all phases if possible. It helps
  with consistency in tone and style.

- If a response feels too generic, tell the AI: "This is too
  generic. Make it specific to [your niche] in [your market]."

- If a response is too short, say: "Expand on this with more
  specific examples for [your market]."

- You can always ask follow-up questions to refine any output
  before moving to the next phase.

- Save all your outputs in one document as you go. You'll want
  the complete set when you start implementing.


READY? Start with Phase 1 below.

`;

    // ── BUILD PHASE SECTIONS ──
    const phaseInstructions = {
      0: 'PASTE THIS PROMPT AS-IS. No previous results needed.',
      1: 'FIRST: Paste your Phase 1 output as context. THEN paste this prompt.',
      2: 'FIRST: Paste your Phase 2 output as context. THEN paste this prompt.',
      3: 'FIRST: Paste your Phase 3 (Dream 5 list) as context. THEN paste this prompt.',
      4: 'FIRST: Paste your Phase 3 and Phase 4 output as context. THEN paste this prompt.',
      5: 'FIRST: Paste your Phase 3 and Phase 4 output as context. THEN paste this prompt.',
      6: 'FIRST: Paste your Phase 3 and Phase 4 output as context. THEN paste this prompt.',
    };

    const body = prompts.map((p, i) => {
      let title = cleanText(p.title).replace(/^Phase \d+[ab]?:\s*/i, '');
      let instruction = phaseInstructions[i] || '';

      return `${divider}
PHASE ${i + 1} of ${prompts.length}: ${title}
${divider}

${instruction}

--- START OF PROMPT (copy everything below this line) ---

${cleanText(p.prompt)}

--- END OF PROMPT (stop copying here) ---`;
    }).join('\n\n\n');

    // ── FOOTER ──
    const footer = `


${divider}
YOU DID IT!
${divider}

You now have a complete Dream 100 referral partner system built
specifically for ${cleanText(niche)} in ${cleanText(formData.geo)}.

NEXT STEPS:
1. Review all your outputs and compile them into one reference doc.
2. Start with your #1 ranked partner from the Dream 5 list.
3. Send that handwritten note FIRST (Phase 6, Script 4).
4. Follow the 90-day plan from Phase 7.

Want us to run all 7 phases automatically and deliver a finished
Word document? Go back to ${theme.brandUrl} and click
"Run All Phases with Claude" on your results page.

${thinDivider}
Generated by ${theme.brandName} - ${theme.brandUrl}
${theme.footerText}
`;

    const fullText = instructions + body + footer;
    const blob = new Blob([fullText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Dream100-Blueprint-${(niche || '').replace(/[^a-z0-9]/gi, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setDlLabel('✓ Downloaded!');
    setTimeout(() => setDlLabel('↓ Download Your Blueprint'), 3000);
  };

  const shareApp = () => {
    const url = theme.brandUrl;
    const text = 'Just built my Dream 100 referral partner blueprint using this free tool. Takes 3 minutes. No login. Try it:';
    if (navigator.share) {
      navigator.share({ title: 'Dream 100 Blueprint Builder', text, url });
    } else {
      navigator.clipboard.writeText(`${text} ${url}`).then(() => alert('Share link copied!'));
    }
  };

  const runWithAI = () => {
    sessionStorage.setItem('d100_run_formData', JSON.stringify({ ...formData, niche }));
    navigate(createPageUrl('RunBlueprint'));
  };

  return (
    <div style={{
      fontFamily: "'Sora', -apple-system, sans-serif",
      background: S.bg,
      minHeight: '100vh',
    }}>
      {/* Page content */}
      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '32px 40px 72px', boxSizing: 'border-box' }}>
        <div style={{
          display: 'grid',
          gridTemplateColumns: '1fr 400px',
          gap: 32,
          alignItems: 'start',
        }} className="out-cols">

          {/* ── LEFT ── */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>

            {/* Warning */}
            <div style={{
              background: S.warnBg, border: `1px solid ${S.warnBd}`,
              borderLeft: `4px solid ${S.warnBd}`, borderRadius: 12,
              padding: '14px 18px', display: 'flex', gap: 11, alignItems: 'flex-start',
            }}>
              <span style={{ fontSize: 19, flexShrink: 0, marginTop: 1 }}>⚠️</span>
              <p style={{ fontSize: 13.5, color: S.warnText, lineHeight: 1.6, margin: 0 }}>
                <strong>Do not try to run all of these prompts at once.</strong> Each prompt builds on the last. Run them in order, one at a time, using the step-by-step instructions in your download. The results compound — skipping steps produces a weaker blueprint.
              </p>
            </div>

            {/* What's in your download */}
            <div style={{
              background: S.white, borderRadius: 14, border: `1px solid ${S.border}`,
              boxShadow: '0 2px 14px rgba(27,42,74,0.06)', overflow: 'hidden',
            }}>
              <div style={{
                padding: '15px 24px', borderBottom: `1px solid ${S.border}`,
                fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
                textTransform: 'uppercase', color: S.muted,
              }}>What's in your download</div>
              <div style={{
                padding: '18px 20px', display: 'grid',
                gridTemplateColumns: '1fr 1fr', gap: 9,
              }} className="dl-grid">
                {DL_ITEMS.map((item, i) => (
                  <div key={i} style={{
                    display: 'flex', alignItems: 'center', gap: 9, padding: '10px 12px',
                    borderRadius: 9, background: S.bg, border: `1px solid ${S.border}`,
                  }}>
                    <span style={{ fontSize: 16 }}>{item.icon}</span>
                    <span style={{ fontSize: 13, color: S.text, fontWeight: 500, lineHeight: 1.4 }}>{item.label}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Prompt list */}
            <div style={{
              background: S.white, borderRadius: 14, border: `1px solid ${S.border}`,
              boxShadow: '0 2px 14px rgba(27,42,74,0.06)', overflow: 'hidden',
            }}>
              <div style={{
                padding: '15px 24px', borderBottom: `1px solid ${S.border}`,
                fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
                textTransform: 'uppercase', color: S.muted,
              }}>The {prompts.length} Prompts Included</div>
              {prompts.map((p, i) => (
                <div key={i} style={{
                  display: 'flex', alignItems: 'center', gap: 13, padding: '12px 24px',
                  borderBottom: i < prompts.length - 1 ? `1px solid ${S.border}` : 'none',
                  background: S.white,
                }}>
                  <div style={{
                    width: 22, height: 22, borderRadius: '50%',
                    background: S.goldPale, border: '1px solid rgba(240,164,34,0.35)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: 9, fontWeight: 700, color: S.gold, flexShrink: 0,
                  }}>{i + 1}</div>
                  <span style={{ fontSize: 13.5, color: S.text, fontWeight: 500, lineHeight: 1.4 }}>{p.title}</span>
                </div>
              ))}
            </div>

          </div>

          {/* ── RIGHT ── */}
          <div style={{ position: 'sticky', top: 76, display: 'flex', flexDirection: 'column', gap: 18 }} className="out-right">

            {/* Run with AI card */}
            <div style={{
              background: S.navy, borderRadius: 16, padding: '26px 24px',
              position: 'relative', overflow: 'hidden', border: '1px solid rgba(240,164,34,0.2)',
            }}>
              {/* glows */}
              <div style={{ position: 'absolute', top: -50, right: -50, width: 200, height: 200, background: 'radial-gradient(circle, rgba(240,164,34,0.16), transparent 65%)', pointerEvents: 'none' }} />
              <div style={{ position: 'absolute', bottom: -30, left: -30, width: 150, height: 150, background: 'radial-gradient(circle, rgba(240,164,34,0.07), transparent 65%)', pointerEvents: 'none' }} />

              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: S.gold, marginBottom: 8, position: 'relative' }}>
                ⚡ Skip the Manual Work
              </div>
              <h3 style={{ fontSize: 21, fontWeight: 800, color: '#fff', margin: '0 0 12px', lineHeight: 1.25, position: 'relative' }}>
                Want us to run all {prompts.length} prompts for you with Claude?
              </h3>
              <p style={{ fontSize: 13.5, color: '#fff', lineHeight: 1.6, margin: '0 0 16px', position: 'relative' }}>
                Instead of working through each prompt yourself, let us run the complete blueprint through Claude AI and deliver a finished, formatted Word document — ready to act on.
              </p>
              <div style={{
                background: 'rgba(255,255,255,0.07)', borderRadius: 10,
                border: '1px solid rgba(255,255,255,0.1)', padding: '12px 14px',
                marginBottom: 18, position: 'relative', fontSize: 13, color: '#fff', lineHeight: 1.5,
              }}>
                Takes about <strong style={{ color: S.gold }}>7–12 minutes</strong> total. Progress shows live as each phase completes.
              </div>
              <button onClick={runWithAI} style={{
                width: '100%', background: S.gold, color: S.navy, border: 'none', borderRadius: 11,
                padding: '16px 24px', fontFamily: "'Sora', sans-serif", fontWeight: 800, fontSize: 16,
                cursor: 'pointer', boxShadow: '0 4px 18px rgba(240,164,34,0.35)',
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
                position: 'relative',
              }}>
                Run All {prompts.length} Phases with Claude →
              </button>
            </div>

            {/* Download card */}
            <div style={{
              background: S.white, borderRadius: 14, border: `1px solid ${S.border}`,
              boxShadow: '0 2px 14px rgba(27,42,74,0.06)', padding: '20px 20px',
            }}>
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: S.muted, marginBottom: 10 }}>
                Prefer to do it yourself?
              </div>
              <p style={{ fontSize: 13, color: S.muted, lineHeight: 1.6, marginBottom: 14 }}>
                Download your personalized Word doc — all {prompts.length} prompts plus step-by-step instructions for running them in ChatGPT or Claude at your own pace.
              </p>
              <button onClick={downloadAll} style={{
                width: '100%', background: S.navy, color: '#fff', border: 'none', borderRadius: 10,
                padding: '13px 18px', fontFamily: "'Sora', sans-serif", fontWeight: 700, fontSize: 14,
                cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
              }}>
                {dlLabel}
              </button>
            </div>

            {/* NurturInk CTA */}
            <div style={{
              background: S.white, borderRadius: 14, border: `1px solid ${S.border}`,
              boxShadow: '0 2px 14px rgba(27,42,74,0.06)', padding: '20px 20px',
            }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: S.gold, marginBottom: 8 }}>
                Brought to you by {theme.brandName}
              </div>
              <h4 style={{ fontSize: 15, fontWeight: 800, color: S.navy, margin: '0 0 8px', lineHeight: 1.35 }}>
                The one move that gets partners to actually respond
              </h4>
              <p style={{ fontSize: 13, color: S.muted, lineHeight: 1.6, margin: '0 0 12px' }}>
                Most agents email. A few will call. The ones who stand out send a <strong>real handwritten card first.</strong> Real pen. Real paper. Your signature. From $2 a card.
              </p>
              <div style={{
                display: 'grid', gridTemplateColumns: '1fr 1fr 1fr',
                background: S.bg, borderRadius: 9, border: `1px solid ${S.border}`,
                overflow: 'hidden', marginBottom: 14,
              }}>
                {[['99%', 'open rate on physical mail'], ['$2', 'per card, no subscription'], ['3–5×', 'vs email']].map(([val, lbl], i) => (
                  <div key={i} style={{
                    padding: '11px 6px', textAlign: 'center',
                    borderRight: i < 2 ? `1px solid ${S.border}` : 'none',
                  }}>
                    <div style={{ fontSize: 19, fontWeight: 800, color: S.gold, lineHeight: 1 }}>{val}</div>
                    <div style={{ fontSize: 10, color: S.muted, marginTop: 3 }}>{lbl}</div>
                  </div>
                ))}
              </div>
              <a href={theme.brandUrl} target="_blank" rel="noopener noreferrer" style={{
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                width: '100%', background: S.navy, color: '#fff', border: 'none', borderRadius: 9,
                padding: '12px 14px', fontFamily: "'Sora', sans-serif", fontWeight: 700, fontSize: 13.5,
                cursor: 'pointer', textDecoration: 'none',
              }}>
                See How {theme.brandName} Works →
              </a>
            </div>

            {/* Share strip */}
            <div style={{ textAlign: 'center', fontSize: 13, color: S.muted }}>
              Know an agent who needs this?{' '}
              <a onClick={shareApp} style={{ color: S.gold, fontWeight: 700, textDecoration: 'none', cursor: 'pointer' }}>
                Share this free tool →
              </a>
            </div>

          </div>
        </div>
      </div>

      {emailModalOpen && (
        <EmailModal
          formData={formData}
          niche={niche}
          prompts={prompts}
          onClose={() => setEmailModalOpen(false)}
        />
      )}

      {/* Footer */}
      <footer style={{
        background: S.navy, color: '#fff', textAlign: 'center',
        padding: '18px 24px', fontSize: 13, lineHeight: 1.6, opacity: 0.6,
      }}>
        This free tool is brought to you by{' '}
        <a href={theme.brandUrl} target="_blank" rel="noopener noreferrer"
          style={{ color: S.gold, textDecoration: 'none', fontWeight: 600, opacity: 1 }}>
          {theme.brandName}
        </a>
        {' '}— {theme.footerText}.
      </footer>

      <style>{`
        @media (max-width: 860px) {
          .out-cols { grid-template-columns: 1fr !important; }
          .out-right { position: static !important; }
        }
        @media (max-width: 600px) {
          .out-cols { padding: 20px 16px 48px !important; gap: 14px !important; }
          .dl-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}