import React, { useState } from "react";
import PhaseCard from "./PhaseCard";
import EmailModal from "./EmailModal";
import NurturinkCTA from "./NurturinkCTA";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";

export default function OutputView({ formData, prompts, onRestart }) {
  const navigate = useNavigate();
  const [emailModalOpen, setEmailModalOpen] = useState(false);
  const [copyAllLabel, setCopyAllLabel] = useState('📋 Copy All 7 Prompts');

  const niche = formData.customNiche
    ? `${formData.nicheBase} — ${formData.customNiche}`
    : formData.nicheBase || '';

  const copyAll = () => {
    const header = `DREAM 100 PARTNER BLUEPRINT\n${niche} | ${formData.geo}\nGenerated by NurturInk — pipeline.nurturink.com\n\n`;
    const body = prompts.map((p, i) =>
      `${'═'.repeat(44)}\nPHASE ${i + 1}: ${p.title}\nOptimized for: ${p.model}\n${'═'.repeat(44)}\n\n${p.prompt}`
    ).join('\n\n\n');
    navigator.clipboard.writeText(header + body).then(() => {
      setCopyAllLabel('✓ All 7 Prompts Copied!');
      setTimeout(() => setCopyAllLabel('📋 Copy All 7 Prompts'), 3000);
    });
  };

  const cleanText = (text) => {
    if (!text) return '';
    return text
      .replace(/[^\x20-\x7E\n\r\t]/g, '') // strip non-ASCII characters
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n');
  };

  const downloadAll = () => {
    const divider = '='.repeat(50);
    const header = `DREAM 100 PARTNER BLUEPRINT\n${cleanText(niche)} | ${cleanText(formData.geo)}\n` +
      `Generated for: ${cleanText(formData.name)}\n` +
      `Generated by NurturInk - pipeline.nurturink.com\n` +
      `Learn how NurturInk helps agents stand out: nurturink.com/realestate\n\n`;
    const body = prompts.map((p, i) =>
      `${divider}\nPHASE ${i + 1}: ${cleanText(p.title)}\nOptimized for: ${cleanText(p.model)}\n${divider}\n\n${cleanText(p.prompt)}`
    ).join('\n\n\n');

    const fullText = cleanText(header + body);
    const blob = new Blob([fullText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Dream100-Blueprint-${(niche || '').replace(/[^a-z0-9]/gi, '-')}-${(formData.geo || '').replace(/[^a-z0-9]/gi, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareApp = () => {
    const url = 'https://pipeline.nurturink.com';
    const text = 'Just built my Dream 100 referral partner blueprint using this free tool from NurturInk. Takes 3 minutes. 7 AI prompts. No login. Try it:';
    if (navigator.share) {
      navigator.share({ title: 'Dream 100 Blueprint Builder', text, url });
    } else {
      navigator.clipboard.writeText(`${text} ${url}`).then(() => {
        alert('Share link copied to clipboard!');
      });
    }
  };

  return (
    <>
      <div className="d100-output-header">
        <div className="d100-success-badge">✓ Your Blueprint is Ready</div>
        <h1>Your {formData.nicheBase || niche} Dream 100 Blueprint</h1>
        <p>{formData.name} · {niche} · {formData.geo}</p>
      </div>

      <div className="d100-output-actions">
        <button className="d100-btn-copy-all" onClick={copyAll}>{copyAllLabel}</button>
        <div className="d100-btn-row-2">
          <button className="d100-btn-email" onClick={() => setEmailModalOpen(true)}>✉ Email Me This</button>
          <button className="d100-btn-email" style={{ borderColor: 'var(--gold)', color: 'var(--gold)' }} onClick={downloadAll}>⬇ Download All</button>
          <button
            className="d100-btn-email"
            style={{ borderColor: '#3B82F6', color: '#3B82F6', fontWeight: 700 }}
            onClick={() => {
              sessionStorage.setItem('d100_run_formData', JSON.stringify({ ...formData, niche }));
              navigate(createPageUrl('RunBlueprint'));
            }}
          >
            ⚡ Run with AI
          </button>
          <button className="d100-btn-restart" onClick={onRestart}>↺</button>
        </div>
      </div>

      {prompts.map((phase, i) => (
        <PhaseCard key={i} phase={phase} index={i} formData={formData} niche={niche} />
      ))}

      <NurturinkCTA />

      <div className="d100-share-strip">
        Know another agent who needs this?<br />
        <a onClick={shareApp}>Share this free tool →</a>
      </div>

      {emailModalOpen && (
        <EmailModal
          formData={formData}
          niche={niche}
          prompts={prompts}
          onClose={() => setEmailModalOpen(false)}
        />
      )}
    </>
  );
}