import React, { useState } from "react";

export default function PhaseCard({ phase, index, formData, niche }) {
  const [open, setOpen] = useState(index === 0);
  const [copyLabel, setCopyLabel] = useState('📋 Copy');
  const [copied, setCopied] = useState(false);

  const copyPhase = () => {
    navigator.clipboard.writeText(phase.prompt).then(() => {
      setCopyLabel('✓ Copied!');
      setCopied(true);
      setTimeout(() => { setCopyLabel('📋 Copy'); setCopied(false); }, 2500);
    });
  };

  const downloadPhase = () => {
    const content = `DREAM 100 BLUEPRINT — Phase ${index + 1}: ${phase.title}\n` +
      `Niche: ${niche} | Market: ${formData.geo}\n` +
      `Optimized for: ${phase.model}\n` +
      `Generated by NurturInk — pipeline.nurturink.com\n\n` +
      `${'═'.repeat(50)}\n\n` +
      phase.prompt +
      `\n\n${'═'.repeat(50)}\n` +
      `Learn how NurturInk helps agents stand out: nurturink.com/realestate`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Dream100-Phase${index + 1}-${phase.title.replace(/[^a-z0-9]/gi, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="d100-phase-card">
      <div className="d100-phase-header" onClick={() => setOpen(!open)}>
        <div style={{ flex: 1 }}>
          <div className="d100-phase-num">Phase {index + 1} of 7</div>
          <div className="d100-phase-title">{phase.title}</div>
          <span className="d100-phase-model-badge">{phase.model}</span>
        </div>
        <div className={`d100-phase-toggle ${open ? 'open' : ''}`}>⌄</div>
      </div>
      {open && (
        <div className="d100-phase-body">
          <p className="d100-model-note">{phase.modelNote}</p>
          <div className="d100-prompt-text">{phase.prompt}</div>
          <div className="d100-phase-btn-row">
            <button className={`d100-phase-copy-btn ${copied ? 'copied' : ''}`} onClick={copyPhase}>{copyLabel}</button>
            <button className="d100-phase-dl-btn" onClick={downloadPhase}>⬇ Download</button>
          </div>
        </div>
      )}
    </div>
  );
}