import React, { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Download, Play, RotateCcw } from "lucide-react";
import { buildPhasePrompts } from "@/components/engine/phasePromptBuilder";
import PhaseRunnerCard from "@/components/runner/PhaseRunnerCard";

export default function RunBlueprint() {
  const navigate = useNavigate();
  const [build, setBuild] = useState(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [activePhase, setActivePhase] = useState(null);
  const [status, setStatus] = useState({});
  const [results, setResults] = useState({});
  const [allDone, setAllDone] = useState(false);
  const resultsRef = useRef({});

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");
    if (!id) { navigate(createPageUrl("Dashboard")); return; }
    base44.entities.Build.filter({ id }).then(res => {
      if (res[0]) setBuild(res[0]);
      setLoading(false);
    });
  }, []);

  const phases = build ? buildPhasePrompts(build) : [];

  async function runAll() {
    setRunning(true);
    setResults({});
    setStatus({});
    setAllDone(false);
    resultsRef.current = {};

    for (const phase of phases) {
      setActivePhase(phase.id);
      setStatus(s => ({ ...s, [phase.id]: "running" }));
      try {
        const response = await base44.functions.invoke("invokeClaude", { prompt: phase.prompt });
        const result = response.data?.result;
        resultsRef.current[phase.id] = result;
        setResults(r => ({ ...r, [phase.id]: result }));
        setStatus(s => ({ ...s, [phase.id]: "done" }));
      } catch (e) {
        setStatus(s => ({ ...s, [phase.id]: "error" }));
        console.error(`Phase ${phase.id} error:`, e);
      }
    }

    setActivePhase(null);
    setRunning(false);
    setAllDone(true);
  }

  function downloadAll() {
    let full = `# DREAM 100 PARTNER BLUEPRINT\n`;
    if (build) full += `${build.niche} — ${build.geography}\n`;
    full += `Generated by NurturInk — NurturInk.com/realestate\n\n`;
    for (const phase of phases) {
      if (resultsRef.current[phase.id]) {
        full += `\n\n${"=".repeat(60)}\n## ${phase.title}\n${"=".repeat(60)}\n\n`;
        full += resultsRef.current[phase.id];
      }
    }
    const blob = new Blob([full], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Dream100_Blueprint_${(build?.name || "output").replace(/[^a-z0-9]/gi, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const completedCount = Object.values(status).filter(s => s === "done").length;

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: "#0A0A12" }}>
      <div className="w-6 h-6 border-2 border-indigo-400 border-t-transparent rounded-full animate-spin" />
    </div>
  );

  if (!build) return (
    <div className="min-h-screen flex items-center justify-center text-slate-400" style={{ backgroundColor: "#0A0A12" }}>
      Build not found.
    </div>
  );

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#0A0A12" }}>
      <div className="max-w-4xl mx-auto px-6 py-8">

        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <Button
            variant="ghost"
            size="icon"
            className="text-slate-400 hover:text-white h-8 w-8"
            onClick={() => navigate(-1)}
          >
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <h1 className="text-white font-bold text-lg">AI Blueprint Runner</h1>
            <p className="text-slate-500 text-xs">{build.niche} · {build.geography}</p>
          </div>
        </div>

        {/* Hero Card */}
        <div className="rounded-2xl p-6 mb-6" style={{ background: "linear-gradient(135deg, #1e3a5f, #1e3860)", border: "1px solid rgba(59,130,246,0.2)" }}>
          <div className="text-xs text-blue-300 uppercase tracking-widest mb-2 opacity-70">NurturInk · Dream 100 Blueprint</div>
          <h2 className="text-white text-xl font-bold mb-1">{build.name}</h2>
          <p className="text-blue-200 text-sm opacity-80">
            This runner will send each of the {phases.length} phases to Claude AI one at a time and display the results below.
          </p>
        </div>

        {/* Controls */}
        <div className="flex flex-wrap gap-3 items-center mb-5">
          <Button
            onClick={allDone ? () => { setAllDone(false); runAll(); } : runAll}
            disabled={running}
            className="btn-gradient gap-2"
          >
            {running ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Running Phase {activePhase} of {phases.length}...
              </>
            ) : allDone ? (
              <><RotateCcw className="w-4 h-4" /> Run Again</>
            ) : (
              <><Play className="w-4 h-4" /> Run All {phases.length} Phases</>
            )}
          </Button>

          {allDone && (
            <Button
              onClick={downloadAll}
              variant="outline"
              className="gap-2 text-sm"
              style={{ borderColor: "rgba(255,255,255,0.25)", color: "#cbd5e1", backgroundColor: "transparent" }}
            >
              <Download className="w-4 h-4" /> Download Full Blueprint
            </Button>
          )}

          {running && (
            <span className="text-slate-500 text-sm">{completedCount} of {phases.length} phases complete</span>
          )}
        </div>

        {/* Progress Bar */}
        {(running || allDone) && (
          <div className="h-1.5 rounded-full mb-6 overflow-hidden" style={{ background: "rgba(255,255,255,0.08)" }}>
            <div
              className="h-full rounded-full transition-all duration-500"
              style={{
                width: `${(completedCount / phases.length) * 100}%`,
                background: "linear-gradient(90deg, #3B82F6, #1D4ED8)"
              }}
            />
          </div>
        )}

        {/* Phase Cards */}
        <div className="flex flex-col gap-4">
          {phases.map(phase => (
            <PhaseRunnerCard
              key={phase.id}
              phase={phase}
              status={status[phase.id]}
              result={results[phase.id]}
              isActive={activePhase === phase.id}
            />
          ))}
        </div>

        {/* All Done Banner */}
        {allDone && (
          <div className="mt-6 rounded-2xl p-5 text-center" style={{ background: "rgba(29,78,216,0.15)", border: "1px solid rgba(59,130,246,0.25)" }}>
            <div className="text-white font-bold text-lg mb-1">✓ All {phases.length} Phases Complete</div>
            <div className="text-slate-400 text-sm">Download your full blueprint above or review each phase below.</div>
          </div>
        )}
      </div>
    </div>
  );
}