import React, { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { base44 } from "@/api/base44Client";
import { buildPhasePrompts } from "@/components/engine/phasePromptBuilder";
import { buildPrompts } from "@/components/dream100/promptBuilder";
import PhaseRunnerCard from "@/components/runner/PhaseRunnerCard";
import RunnerProgressCard from "@/components/runner/RunnerProgressCard";
import RunnerNurturInkCTA from "@/components/runner/RunnerNurturInkCTA";

export default function RunBlueprint() {
  const navigate = useNavigate();
  const [build, setBuild] = useState(null);
  const [landingData, setLandingData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [activePhase, setActivePhase] = useState(null);
  const [status, setStatus] = useState({});
  const [results, setResults] = useState({});
  const [errors, setErrors] = useState({});
  const [allDone, setAllDone] = useState(false);
  const [exportingWord, setExportingWord] = useState(false);
  const resultsRef = useRef({});

  useEffect(() => {
    const stored = sessionStorage.getItem('d100_run_formData');
    if (stored) {
      setLandingData(JSON.parse(stored));
      setLoading(false);
      return;
    }
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");
    if (!id) { navigate(createPageUrl("Landing")); return; }
    base44.entities.Build.filter({ id }).then(res => {
      if (res[0]) setBuild(res[0]);
      setLoading(false);
    });
  }, []);

  const phases = landingData
    ? buildPrompts(landingData).map((p, i) => ({ id: p.id !== undefined ? p.id : i + 1, title: p.title, prompt: p.prompt, isSearch: p.isSearch }))
    : build
    ? buildPhasePrompts(build)
    : [];

  const displayName = landingData
    ? `${landingData.niche || landingData.nicheBase} · ${landingData.geo}`
    : build
    ? build.name
    : "";

  async function runAll() {
    setRunning(true);
    setResults({});
    setStatus({});
    setAllDone(false);
    resultsRef.current = {};

    for (const phase of phases) {
      setActivePhase(phase.id);
      setStatus(s => ({ ...s, [phase.id]: "running" }));
      try {
        const invokeParams = phase.isSearch
          ? { prompt: phase.prompt, model: "claude-sonnet-4-6", add_context_from_internet: true }
          : { prompt: phase.prompt, model: "claude-sonnet-4-6" };
        const response = await base44.functions.invoke("invokeClaude", invokeParams);
        const result = response.data?.result;
        resultsRef.current[phase.id] = result;
        setResults(r => ({ ...r, [phase.id]: result }));
        setStatus(s => ({ ...s, [phase.id]: "done" }));
      } catch (e) {
        setStatus(s => ({ ...s, [phase.id]: "error" }));
        console.error(`Phase ${phase.id} error:`, e);
      }
    }

    setActivePhase(null);
    setRunning(false);
    setAllDone(true);
  }

  async function downloadWord() {
    setExportingWord(true);
    const config = landingData
      ? { agentName: landingData.name || "Agent", niche: landingData.niche || landingData.nicheBase || "Real Estate", subniche: "", market: landingData.geo || "My Market", idealClient: landingData.client || "" }
      : build
      ? { agentName: build.name, niche: build.niche, subniche: "", market: build.geography, idealClient: "" }
      : {};
    const res = await fetch("/functions/exportToWord", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ config, phaseResults: resultsRef.current }),
    });
    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.error || "Export failed");
    }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Dream100_Blueprint_${(config.agentName || "Blueprint").replace(/\s+/g, "_")}.docx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setExportingWord(false);
  }

  function downloadAll() {
    let full = `# DREAM 100 PARTNER BLUEPRINT\n`;
    if (build) full += `${build.niche} — ${build.geography}\n`;
    full += `Generated by NurturInk — NurturInk.com/realestate\n\n`;
    for (const phase of phases) {
      if (resultsRef.current[phase.id]) {
        full += `\n\n${"=".repeat(60)}\n## ${phase.title}\n${"=".repeat(60)}\n\n`;
        full += resultsRef.current[phase.id];
      }
    }
    const blob = new Blob([full], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Dream100_Blueprint_${(displayName || "output").replace(/[^a-z0-9]/gi, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const completedCount = Object.values(status).filter(s => s === "done").length;
  const firstDonePhase = phases.find(p => status[p.id] === "done");

  if (loading) return (
    <div style={{ minHeight: "100vh", background: "#F4F1EC", display: "flex", alignItems: "center", justifyContent: "center" }}>
      <div style={{ width: 36, height: 36, border: "3px solid #EDE8E0", borderTopColor: "#C9973A", borderRadius: "50%", animation: "runnerSpin 0.8s linear infinite" }} />
    </div>
  );

  if (!landingData && !build) return (
    <div style={{ minHeight: "100vh", background: "#F4F1EC", display: "flex", alignItems: "center", justifyContent: "center", color: "#5A6278", fontFamily: "'Sora', sans-serif" }}>
      Build not found.
    </div>
  );

  return (
    <div style={{ background: "#F4F1EC", minHeight: "100vh", fontFamily: "'Sora', -apple-system, sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700;800&display=swap');
        @keyframes runnerSpin { to { transform: rotate(360deg); } }
        @keyframes runnerBlink { 0%,100%{opacity:1} 50%{opacity:0.4} }
        .runner-phase-list > * + * { margin-top: 10px; }
        @media (max-width: 860px) {
          .runner-two-col { grid-template-columns: 1fr !important; }
          .runner-right-col { position: static !important; }
        }
        @media (max-width: 600px) {
          .runner-body { padding: 20px 16px 60px !important; }
          .runner-nav-inner { padding: 0 16px !important; }
        }
      `}</style>

      {/* Sticky Nav */}
      <div style={{ background: "#1B2A4A", boxShadow: "0 2px 20px rgba(0,0,0,0.25)", position: "sticky", top: 0, zIndex: 100 }}>
        <div className="runner-nav-inner" style={{ maxWidth: 1160, margin: "0 auto", padding: "0 40px", height: 60, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          {/* Left */}
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <button
              onClick={() => navigate(-1)}
              style={{ background: "rgba(255,255,255,0.1)", border: "none", borderRadius: 8, width: 32, height: 32, cursor: "pointer", color: "#fff", fontSize: 18, display: "flex", alignItems: "center", justifyContent: "center" }}
            >←</button>
            <div>
              <div style={{ color: "#fff", fontWeight: 700, fontSize: 15, lineHeight: 1.2 }}>AI Blueprint Runner</div>
              <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 11, lineHeight: 1.4 }}>{displayName}</div>
            </div>
          </div>

          {/* Right */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            {(running || allDone || completedCount > 0) && (
              <span style={{ fontSize: 12, color: "rgba(255,255,255,0.4)", marginRight: 4 }}>{completedCount} of {phases.length} complete</span>
            )}

            {allDone && (
              <>
                <button
                  onClick={downloadAll}
                  style={{ background: "transparent", color: "rgba(255,255,255,0.75)", border: "1px solid rgba(255,255,255,0.18)", borderRadius: 8, padding: "8px 14px", fontFamily: "'Sora', sans-serif", fontWeight: 600, fontSize: 13, cursor: "pointer" }}
                >↓ Markdown</button>
                <button
                  onClick={downloadWord}
                  disabled={exportingWord}
                  style={{ background: "rgba(201,151,58,0.15)", color: "#E8B55A", border: "1px solid rgba(201,151,58,0.35)", borderRadius: 8, padding: "8px 14px", fontFamily: "'Sora', sans-serif", fontWeight: 600, fontSize: 13, cursor: exportingWord ? "not-allowed" : "pointer", display: "flex", alignItems: "center", gap: 6 }}
                >
                  {exportingWord ? (
                    <><div style={{ width: 12, height: 12, border: "2px solid rgba(201,151,58,0.3)", borderTopColor: "#C9973A", borderRadius: "50%", animation: "runnerSpin 0.8s linear infinite" }} /> Building...</>
                  ) : "📄 Word Doc"}
                </button>
              </>
            )}

            {running ? (
              <button
                disabled
                style={{ background: "rgba(255,255,255,0.1)", color: "rgba(255,255,255,0.5)", border: "none", borderRadius: 8, padding: "8px 16px", fontFamily: "'Sora', sans-serif", fontWeight: 800, fontSize: 13, cursor: "not-allowed", display: "flex", alignItems: "center", gap: 6 }}
              >
                <div style={{ width: 12, height: 12, border: "2px solid rgba(255,255,255,0.3)", borderTopColor: "rgba(255,255,255,0.8)", borderRadius: "50%", animation: "runnerSpin 0.8s linear infinite" }} />
                Phase {activePhase}/{phases.length} Running...
              </button>
            ) : (
              <button
                onClick={allDone ? () => { setAllDone(false); runAll(); } : runAll}
                style={{ background: "#C9973A", color: "#1B2A4A", border: "none", borderRadius: 8, padding: "8px 16px", fontFamily: "'Sora', sans-serif", fontWeight: 800, fontSize: 13, cursor: "pointer" }}
              >
                {allDone ? "↺ Run Again" : `▶ Run All ${phases.length} Phases`}
              </button>
            )}
          </div>
        </div>

        {/* Progress bar */}
        {(running || allDone) && (
          <div style={{ height: 3, background: "rgba(255,255,255,0.08)" }}>
            <div style={{ height: "100%", width: `${(completedCount / phases.length) * 100}%`, background: "linear-gradient(90deg, #C9973A, #E8B55A)", transition: "width 0.6s ease" }} />
          </div>
        )}
      </div>

      {/* Body */}
      <div className="runner-body" style={{ maxWidth: 1160, margin: "0 auto", padding: "32px 40px 80px" }}>

        {/* Context card */}
        <div style={{
          background: "#1B2A4A", borderRadius: 14, padding: "22px 26px",
          marginBottom: 24, position: "relative", overflow: "hidden",
        }}>
          <div style={{ position: "absolute", top: -30, right: -30, width: 160, height: 160, background: "radial-gradient(circle, rgba(201,151,58,0.13), transparent 65%)", pointerEvents: "none" }} />
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#E8B55A", marginBottom: 6 }}>NurturInk · Dream 100 Blueprint</div>
          <div style={{ color: "#fff", fontWeight: 800, fontSize: 17, marginBottom: 8, lineHeight: 1.3, fontFamily: "'Sora', sans-serif" }}>{displayName}</div>
          <div style={{ color: "rgba(255,255,255,0.55)", fontSize: 13.5, lineHeight: 1.6 }}>
            Sending each of the {phases.length} phases to Claude AI one at a time.{" "}
            <strong style={{ color: "rgba(255,255,255,0.85)" }}>Each phase takes 1–6 minutes.</strong>
          </div>
        </div>

        {/* Two-column layout */}
        <div className="runner-two-col" style={{ display: "grid", gridTemplateColumns: "1fr 380px", gap: 32, alignItems: "start" }}>

          {/* LEFT */}
          <div>
            {/* Warning */}
            <div style={{
              background: "#FEF3C7", border: "1px solid #F59E0B",
              borderLeft: "4px solid #F59E0B", borderRadius: 12,
              padding: "14px 18px", marginBottom: 20,
              display: "flex", gap: 12, alignItems: "flex-start",
            }}>
              <span style={{ fontSize: 19, flexShrink: 0, marginTop: 1 }}>⏳</span>
              <p style={{ fontSize: 14, color: "#92400E", lineHeight: 1.6, margin: 0 }}>
                <strong>Don't stop this process or navigate away while it's running.</strong>{" "}
                Each phase builds on the last. If interrupted, use Run Again to restart from the beginning.
              </p>
            </div>

            {/* Phase cards */}
            <div className="runner-phase-list">
              {phases.map((phase, idx) => (
                <PhaseRunnerCard
                  key={phase.id}
                  phase={phase}
                  status={status[phase.id]}
                  result={results[phase.id]}
                  isActive={activePhase === phase.id}
                  defaultExpanded={firstDonePhase?.id === phase.id}
                />
              ))}
            </div>

            {/* All done banner */}
            {allDone && (
              <div style={{
                marginTop: 20, padding: "22px 24px", borderRadius: 14,
                background: "rgba(45,106,79,0.06)", border: "1px solid rgba(45,106,79,0.2)",
                textAlign: "center",
              }}>
                <div style={{ fontSize: 12, color: "#2D6A4F", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 }}>✓ Complete</div>
                <div style={{ fontSize: 18, fontWeight: 800, color: "#1B2A4A", marginBottom: 6, fontFamily: "'Sora', sans-serif" }}>All {phases.length} Phases Complete</div>
                <div style={{ fontSize: 14, color: "#5A6278" }}>Download your full blueprint using the buttons in the nav above.</div>
              </div>
            )}
          </div>

          {/* RIGHT */}
          <div className="runner-right-col" style={{ position: "sticky", top: 76, display: "flex", flexDirection: "column", gap: 16 }}>
            <RunnerProgressCard
              phases={phases}
              status={status}
              activePhase={activePhase}
              completedCount={completedCount}
            />
            <RunnerNurturInkCTA />
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer style={{ background: "#1B2A4A", color: "rgba(255,255,255,0.4)", textAlign: "center", padding: "18px 24px", fontSize: 12, lineHeight: 1.6 }}>
        <a href="https://nurturink.com/realestate" target="_blank" rel="noreferrer" style={{ color: "#C9973A", textDecoration: "none" }}>NurturInk.com</a>
        {" · "}the handwritten follow-up system for relationship-driven sales professionals
      </footer>
    </div>
  );
}