import React, { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { base44 } from "@/api/base44Client";
import { buildPhasePrompts } from "@/components/engine/phasePromptBuilder";
import { buildPrompts } from "@/components/dream100/promptBuilder";
import PhaseRunnerCard from "@/components/runner/PhaseRunnerCard";
import Dream100Styles from "@/components/dream100/Dream100Styles";

export default function RunBlueprint() {
  const navigate = useNavigate();
  const [build, setBuild] = useState(null);
  const [landingData, setLandingData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [activePhase, setActivePhase] = useState(null);
  const [status, setStatus] = useState({});
  const [results, setResults] = useState({});
  const [allDone, setAllDone] = useState(false);
  const [exportingWord, setExportingWord] = useState(false);
  const resultsRef = useRef({});

  useEffect(() => {
    const stored = sessionStorage.getItem('d100_run_formData');
    if (stored) {
      setLandingData(JSON.parse(stored));
      setLoading(false);
      return;
    }
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");
    if (!id) { navigate(createPageUrl("Landing")); return; }
    base44.entities.Build.filter({ id }).then(res => {
      if (res[0]) setBuild(res[0]);
      setLoading(false);
    });
  }, []);

  const phases = landingData
    ? buildPrompts(landingData).map((p, i) => ({ id: p.id !== undefined ? p.id : i + 1, title: p.title, prompt: p.prompt, isSearch: p.isSearch }))
    : build
    ? buildPhasePrompts(build)
    : [];

  const displayName = landingData
    ? `${landingData.niche || landingData.nicheBase} · ${landingData.geo}`
    : build
    ? build.name
    : "";

  async function runAll() {
    setRunning(true);
    setResults({});
    setStatus({});
    setAllDone(false);
    resultsRef.current = {};

    for (const phase of phases) {
      setActivePhase(phase.id);
      setStatus(s => ({ ...s, [phase.id]: "running" }));
      try {
        const invokeParams = phase.isSearch
          ? { prompt: phase.prompt, model: "claude-sonnet-4-6", add_context_from_internet: true }
          : { prompt: phase.prompt, model: "claude-sonnet-4-6" };
        const response = await base44.functions.invoke("invokeClaude", invokeParams);
        const result = response.data?.result;
        resultsRef.current[phase.id] = result;
        setResults(r => ({ ...r, [phase.id]: result }));
        setStatus(s => ({ ...s, [phase.id]: "done" }));
      } catch (e) {
        setStatus(s => ({ ...s, [phase.id]: "error" }));
        console.error(`Phase ${phase.id} error:`, e);
      }
    }

    setActivePhase(null);
    setRunning(false);
    setAllDone(true);
  }

  async function downloadWord() {
    setExportingWord(true);
    const config = landingData
      ? { agentName: landingData.name || "Agent", niche: landingData.niche || landingData.nicheBase || "Real Estate", subniche: "", market: landingData.geo || "My Market", idealClient: landingData.client || "" }
      : build
      ? { agentName: build.name, niche: build.niche, subniche: "", market: build.geography, idealClient: "" }
      : {};
    const res = await fetch("/functions/exportToWord", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ config, phaseResults: resultsRef.current }),
    });
    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.error || "Export failed");
    }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Dream100_Blueprint_${(config.agentName || "Blueprint").replace(/\s+/g, "_")}.docx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setExportingWord(false);
  }

  function downloadAll() {
    let full = `# DREAM 100 PARTNER BLUEPRINT\n`;
    if (build) full += `${build.niche} — ${build.geography}\n`;
    full += `Generated by NurturInk — NurturInk.com/realestate\n\n`;
    for (const phase of phases) {
      if (resultsRef.current[phase.id]) {
        full += `\n\n${"=".repeat(60)}\n## ${phase.title}\n${"=".repeat(60)}\n\n`;
        full += resultsRef.current[phase.id];
      }
    }
    const blob = new Blob([full], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Dream100_Blueprint_${(displayName || "output").replace(/[^a-z0-9]/gi, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const completedCount = Object.values(status).filter(s => s === "done").length;

  if (loading) return (
    <>
      <Dream100Styles />
      <div style={{ minHeight: "100vh", background: "var(--cream)", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div className="d100-spinner" />
      </div>
    </>
  );

  if (!landingData && !build) return (
    <>
      <Dream100Styles />
      <div style={{ minHeight: "100vh", background: "var(--cream)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text-muted)" }}>
        Build not found.
      </div>
    </>
  );

  return (
    <>
      <Dream100Styles />

      {/* Sticky Nav */}
      <div className="d100-sticky-nav">
        <div className="d100-nav-top">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <button
              onClick={() => navigate(-1)}
              style={{ background: "rgba(255,255,255,0.1)", border: "none", borderRadius: 8, width: 32, height: 32, cursor: "pointer", color: "white", fontSize: 16, display: "flex", alignItems: "center", justifyContent: "center" }}
            >←</button>
            <div>
              <div style={{ color: "white", fontWeight: 700, fontSize: 15, fontFamily: "'Sora', sans-serif" }}>AI Blueprint Runner</div>
              <div style={{ color: "rgba(255,255,255,0.5)", fontSize: 12 }}>{displayName}</div>
            </div>
          </div>

          {/* Controls in nav */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <button
              onClick={allDone ? () => { setAllDone(false); runAll(); } : runAll}
              disabled={running}
              style={{
                background: running ? "rgba(255,255,255,0.1)" : "var(--gold)",
                color: running ? "rgba(255,255,255,0.5)" : "var(--navy)",
                border: "none", borderRadius: 8, padding: "8px 18px",
                fontFamily: "'Sora', sans-serif", fontWeight: 700, fontSize: 14,
                cursor: running ? "not-allowed" : "pointer",
                display: "flex", alignItems: "center", gap: 6
              }}
            >
              {running ? (
                <>
                  <div style={{ width: 12, height: 12, border: "2px solid rgba(255,255,255,0.3)", borderTopColor: "rgba(255,255,255,0.8)", borderRadius: "50%", animation: "d100spin 0.8s linear infinite" }} />
                  Phase {activePhase}/{phases.length}
                </>
              ) : allDone ? "↺ Run Again" : `▶ Run All ${phases.length} Phases`}
            </button>

            {allDone && (
              <>
                <button
                  onClick={downloadAll}
                  style={{ background: "rgba(255,255,255,0.1)", color: "rgba(255,255,255,0.85)", border: "1px solid rgba(255,255,255,0.2)", borderRadius: 8, padding: "8px 14px", fontFamily: "'Sora', sans-serif", fontWeight: 600, fontSize: 13, cursor: "pointer" }}
                >↓ Markdown</button>
                <button
                  onClick={downloadWord}
                  disabled={exportingWord}
                  style={{ background: "rgba(201,151,58,0.15)", color: "var(--gold-light)", border: "1px solid rgba(201,151,58,0.35)", borderRadius: 8, padding: "8px 14px", fontFamily: "'Sora', sans-serif", fontWeight: 600, fontSize: 13, cursor: exportingWord ? "not-allowed" : "pointer", display: "flex", alignItems: "center", gap: 6 }}
                >
                  {exportingWord ? (
                    <><div style={{ width: 12, height: 12, border: "2px solid rgba(201,151,58,0.3)", borderTopColor: "var(--gold)", borderRadius: "50%", animation: "d100spin 0.8s linear infinite" }} /> Building...</>
                  ) : "📄 Download Word"}
                </button>
              </>
            )}
          </div>
        </div>

        {/* Progress bar */}
        {(running || allDone) && (
          <div style={{ height: 3, background: "rgba(255,255,255,0.08)" }}>
            <div style={{ height: "100%", width: `${(completedCount / phases.length) * 100}%`, background: "var(--gold)", transition: "width 0.5s ease" }} />
          </div>
        )}
      </div>

      {/* Main content */}
      <div className="d100-main" style={{ maxWidth: 720 }}>

        {/* Hero info card */}
        <div className="d100-form-card" style={{ marginBottom: 20, background: "var(--navy)", borderColor: "rgba(255,255,255,0.1)" }}>
          <div style={{ fontSize: 11, color: "var(--gold-light)", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 700, marginBottom: 6 }}>NurturInk · Dream 100 Blueprint</div>
          <div style={{ color: "white", fontWeight: 800, fontSize: 18, marginBottom: 4, fontFamily: "'Sora', sans-serif" }}>{landingData ? displayName : build?.name}</div>
          <div style={{ color: "rgba(255,255,255,0.65)", fontSize: 14, lineHeight: 1.5 }}>
            This runner will send each of the {phases.length} phases to Claude AI one at a time and display the results below.
          </div>
          {running && (
            <div style={{ marginTop: 12, fontSize: 13, color: "rgba(255,255,255,0.5)" }}>
              {completedCount} of {phases.length} phases complete
            </div>
          )}
        </div>

        {/* Phase Cards */}
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {phases.map(phase => (
            <PhaseRunnerCard
              key={phase.id}
              phase={phase}
              status={status[phase.id]}
              result={results[phase.id]}
              isActive={activePhase === phase.id}
            />
          ))}
        </div>

        {/* All Done Banner */}
        {allDone && (
          <div className="d100-form-card" style={{ marginTop: 20, textAlign: "center", background: "rgba(45,106,79,0.06)", borderColor: "rgba(45,106,79,0.2)" }}>
            <div style={{ fontSize: 13, color: "var(--success)", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 }}>✓ Complete</div>
            <div style={{ fontSize: 18, fontWeight: 800, color: "var(--navy)", marginBottom: 6, fontFamily: "'Sora', sans-serif" }}>All {phases.length} Phases Complete</div>
            <div style={{ fontSize: 14, color: "var(--text-muted)" }}>Download your full blueprint above or review each phase below.</div>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="d100-site-footer">
        <a href="https://nurturink.com/realestate" target="_blank" rel="noreferrer">NurturInk.com</a>
        {" · "}the handwritten follow-up system for relationship-driven sales professionals
      </div>
    </>
  );
}